-- 013_performance_indexes_and_primary_keys.sql
-- Adds missing indexes for foreign keys and primary keys for backup tables
-- Generated by GitHub Copilot, 2025-09-05

BEGIN;

-- 1. Add missing indexes for foreign keys
CREATE INDEX IF NOT EXISTS idx_account_links_user_id ON public.account_links(user_id);
CREATE INDEX IF NOT EXISTS idx_accounts_institution_id ON public.accounts(institution_id);
CREATE INDEX IF NOT EXISTS idx_budget_categories_budget_id ON public.budget_categories(budget_id);
CREATE INDEX IF NOT EXISTS idx_budget_categories_user_id ON public.budget_categories(user_id);
CREATE INDEX IF NOT EXISTS idx_budgets_user_id ON public.budgets(user_id);
CREATE INDEX IF NOT EXISTS idx_goals_user_id ON public.goals(user_id);
CREATE INDEX IF NOT EXISTS idx_manual_assets_user_id ON public.manual_assets(user_id);
CREATE INDEX IF NOT EXISTS idx_mcc_category_map_category_id ON public.mcc_category_map(category_id);
CREATE INDEX IF NOT EXISTS idx_merchants_default_category_id ON public.merchants(default_category_id);
CREATE INDEX IF NOT EXISTS idx_net_worth_snapshots_user_id ON public.net_worth_snapshots(user_id);
CREATE INDEX IF NOT EXISTS idx_tags_user_id ON public.tags(user_id);
-- Drop duplicate index if it exists
DROP INDEX IF EXISTS idx_transaction_edits_fk_te_user;
CREATE INDEX IF NOT EXISTS idx_transaction_edits_user_id ON public.transaction_edits(user_id);
CREATE INDEX IF NOT EXISTS idx_transaction_tags_tag_id ON public.transaction_tags(tag_id);
CREATE INDEX IF NOT EXISTS idx_transactions_account_id ON public.transactions(account_id);
CREATE INDEX IF NOT EXISTS idx_transactions_goal_id ON public.transactions(goal_id);
CREATE INDEX IF NOT EXISTS idx_transactions_merchant_id ON public.transactions(merchant_id);
CREATE INDEX IF NOT EXISTS idx_transactions_fk_transactions_edited_by ON public.transactions(edited_by);

COMMIT;
